# Generated by Django 4.1.3 on 2022-12-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('barcode', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='subcategory', max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.category')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name of component', max_length=200)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('stock', models.IntegerField()),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('fine', models.FloatField(default=1)),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.borrower')),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.component')),
            ],
        ),
    ]
