# Generated by Django 4.1.3 on 2022-12-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_subcategory_image_alter_component_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowlist',
            name='pieces',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
